CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    category    VARCHAR(255),
    price       DOUBLE PRECISION                        NOT NULL,
    quantity    INTEGER                                 NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

INSERT INTO product (category,description,"name",price,quantity) VALUES
('ELECTRONICS','High-end laptop with 16GB RAM and 512GB SSD','Laptop Pro',1200.0,10),
('FURNITURE','Wooden office desk with drawers','Office Desk',350.0,5),
('CLOTHING','Lightweight shoes for running','Running Shoes',75.0,20),
('FOOD','Fresh organic apples from local farm','Organic Apples',3.5,100),
('TOYS','Soft plush teddy bear','Teddy Bear',25.0,40),
('BOOKS','Epic fantasy novel with dragons','Fantasy Novel',15.0,30),
('SPORTS','FIFA-approved soccer ball','Soccer Ball',30.0,25),
('BEAUTY','Natural shampoo with aloe vera','Shampoo',8.99,50),
('AUTOMOTIVE','Fast USB car charger','Car Charger',14.99,35),
('HEALTHCARE','1000mg Vitamin C tablets','Vitamin C',12.5,60);
INSERT INTO product (category,description,"name",price,quantity) VALUES
('ELECTRONICS','Noise-cancelling over-ear headphones','Bluetooth Headphones',89.99,15),
('FURNITURE','Modern glass dining table','Dining Table',500.0,2),
('CLOTHING','Waterproof and insulated jacket','Winter Jacket',120.0,12),
('FOOD','1-liter organic whole milk','Milk',1.99,80),
('TOYS','Remote-controlled sports car','RC Car',45.0,18),
('BOOKS','Advanced high school physics book','Science Textbook',60.0,22),
('SPORTS','Non-slip mat for yoga and pilates','Yoga Mat',22.0,35),
('BEAUTY','Anti-aging face cream with retinol','Face Cream',34.5,25),
('AUTOMOTIVE','All-season windshield wiper blades','Wiper Blades',19.99,30),
('HEALTHCARE','Ibuprofen tablets 200mg','Pain Reliever',6.99,100);
INSERT INTO product (category,description,"name",price,quantity) VALUES
('ELECTRONICS','Latest model with AMOLED display','Smartphone',899.0,8),
('FURNITURE','5-tier wooden bookshelf','Bookshelf',120.0,6),
('CLOTHING','Slim-fit blue jeans','Jeans',40.0,18),
('FOOD','Whole grain bread loaf','Bread',2.5,70),
('TOYS','Creative building block set','Lego Set',60.0,20),
('BOOKS','Gripping detective story','Mystery Novel',10.0,28),
('SPORTS','Professional-grade tennis racket','Tennis Racket',90.0,10),
('BEAUTY','Matte finish long-lasting lipstick','Lipstick',12.0,40),
('AUTOMOTIVE','Car air freshener - citrus scent','Air Freshener',5.0,45),
('HEALTHCARE','Compact emergency kit for home or travel','First Aid Kit',25.0,15);
